---
title: "Lab Week 8"
author: "Heili Lowman"
date: "3/8/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages.

```{r packages}

library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)

```

# Column graph of Texas oil spills.

```{r data}

spills <- read_csv("oil_spills.csv") #Load data.

df <- spills %>% 
  filter(`Accident State`=="TX" & `Accident Year` < 2017) %>%  # Because the name has a space in it it must be bounded by the little backwards apostrophes. This chooses only Texan data before 2017.
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`))

colnames(df) <- c("Year", "Loss") # Rename columns.  

ggplot(df, aes(x = Year, y = Loss)) +
  geom_col() # Creates a column graph.

```

# Leaflet plot of spill locations in TX in 2016

```{r leaflet}

df_loc <- spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`) # Create a new dataframe filtering 2016 Texas data and keep only lat, long, and loss columns.

colnames(df_loc) <- c("latitude", "longitude", "net_loss") # Changes the column names.

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326) # Convert data frame information into shape data. Remember to always list longitude first, otherwise your map will appear flipped by 90 degrees.

leaflet(oil_sf) %>% 
  addTiles() %>% #Adding face map.
  addMarkers() #Net Loss is the only variable, so you don't have to specify.
  

```

# Tmap plot with the Texas state shapefile

```{r tmap}

states <- st_read(dsn = ".", layer = "states" ) #???

tex_border <- states %>% # From the states shapefile in our folder.
  filter(STATE_NAME == "Texas") %>%  # Filter out only the state of Texas.
  st_transform(4326) # Coordinate reference system.

plot(tex_border)

tm_shape(tex_border) + # Create a map using tmap.
  tm_polygons() + # Plot the TX border as a polygon.
  tm_shape(oil_sf) + # Add in oil spill points from above.
  tm_dots(size = 0.3) # Edits size of points.

```

# Convert the data to spatial points patterns (combination of the point data and the bounding window)

```{r point_pattern}

spill_spatial <- as(oil_sf, "Spatial") # Converting from simple features back to a data frame.
spill_ppp <- as(spill_spatial, "ppp") # Convert the new data frame to a point pattern.

tx_sp <- as(tex_border, "Spatial") # Convert texas border data back into a data frame.
tx_owin <-as(tx_sp, "owin") # Sets the TX boundary as the window.

all_ppp <- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin) # Omits points that don't align between the points pattern and the window we define.

```






